### ISSUE TITLE
Blocksize and Upload error

### ISSUE THREAD

**Issue by samapriya** [tracek/gee_asset_manager#23]
Traceback (most recent call last):
  File "/home/samapriya/Downloads/gee/gee_asset_manager/batch_uploader.py", line 83, in upload
    properties, multipart_upload, nodata_value)
  File "/home/samapriya/.local/lib/python2.7/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/samapriya/.local/lib/python2.7/site-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/home/samapriya/.local/lib/python2.7/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/home/samapriya/.local/lib/python2.7/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/home/samapriya/Downloads/gee/gee_asset_manager/batch_uploader.py", line 133, in __upload_to_gcs_and_start_ingestion_task
    nodata=nodata_value)
  File "/home/samapriya/Downloads/gee/gee_asset_manager/batch_uploader.py", line 222, in __upload_file
    resp = session.post(upload_url, files=files)
  File "/home/samapriya/.local/lib/python2.7/site-packages/requests/sessions.py", line 522, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/samapriya/.local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/samapriya/.local/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/home/samapriya/.local/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/home/samapriya/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/home/samapriya/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 363, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 873, in send
    self.sock.sendall(data)
  File "/home/samapriya/.local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 253, in sendall
    sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
  File "/home/samapriya/.local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 242, in _send_until_done
    return self.connection.send(data)
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 1256, in send
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 1166, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
SysCallError: (104, 'ECONNRESET')

**Comment by tracek** [comment]
I am afraid I am not able to reproduce the issue. Can you post what version of pyOpenSSL and libssl-dev you have?

**Comment by samapriya** [comment]
Thanks Lukasz,
I should have closed this issue, I upgraded my packages and no longer seem to be getting this issue.

Warm Wishes,
Sam

**Comment by tracek** [comment]
Thanks! I will leave re-open the issue and add handling for SSL errors. Often enough it might be just a hiccup that could be resolved by simply resubmitting the job. Currently I retry on EE errors, but not on these.
