### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by wle0001** [tracek/gee_asset_manager#25]
I receive syntax errors when trying upload:

2017-03-22 12:12:28,841 :: root :: WARNING :: Collection users/wle0001/test already exists
2017-03-22 12:12:29,273 :: root :: INFO :: Processing image 1 out of 1: /Users/wellenbu/Documents/HKH/WheatMapping/Downloadscripts/Corrected/Sample/Corrected2.tif
2017-03-22 12:12:30,083 :: root :: ERROR :: Upload of Corrected2 has failed.
Traceback (most recent call last):
  File "/Users/wellenbu/Downloads/gee_asset_manager/gee_asset_manager/batch_uploader.py", line 83, in upload
    properties, multipart_upload, nodata_value)
  File "/Users/wellenbu/anaconda2/lib/python2.7/site-packages/retrying.py", line 92, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/Users/wellenbu/anaconda2/lib/python2.7/site-packages/retrying.py", line 247, in call
    return attempt.get(self._wrap_exception)
  File "/Users/wellenbu/anaconda2/lib/python2.7/site-packages/retrying.py", line 285, in get
    reraise(self.value[0], self.value[1], self.value[2])
  File "/Users/wellenbu/anaconda2/lib/python2.7/site-packages/retrying.py", line 241, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/Users/wellenbu/Downloads/gee_asset_manager/gee_asset_manager/batch_uploader.py", line 133, in __upload_to_gcs_and_start_ingestion_task
    nodata=nodata_value)
  File "/Users/wellenbu/Downloads/gee_asset_manager/gee_asset_manager/batch_uploader.py", line 207, in __upload_file
    upload_url = __get_upload_url(session)
  File "/Users/wellenbu/Downloads/gee_asset_manager/gee_asset_manager/batch_uploader.py", line 201, in __get_upload_url
    d = ast.literal_eval(r.text)
  File "/Users/wellenbu/anaconda2/lib/python2.7/ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/Users/wellenbu/anaconda2/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    <HTML><HEAD>
    ^
SyntaxError: invalid syntax

Any ideas?

**Comment by tracek** [comment]
Thanks for reporting! Should be fixed now. Somehow the first time I am requesting the url for upload, the request does not go through. Second time the charm. Please let me know if it works for you.

**Comment by wle0001** [comment]
Thanks! Seems to be fixed!
