### ISSUE TITLE
Too Many Redirects 

### ISSUE THREAD

**Issue by rosepetersky** [tracek/gee_asset_manager#31]
geebam was working fine yesterday so I'm not sure what happened.

Now when I try to upload assets it gives me this error:

2017-05-25 17:55:11,063 :: root :: ERROR :: Upload of SWE_20031007 has failed.
Traceback (most recent call last):
  File "/Users/rpetersky/gee_asset_manager/gee_asset_manager/batch_uploader.py", line 83, in upload
    properties, multipart_upload, nodata_value)
  File "build/bdist.macosx-10.6-intel/egg/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "build/bdist.macosx-10.6-intel/egg/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "build/bdist.macosx-10.6-intel/egg/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "build/bdist.macosx-10.6-intel/egg/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/Users/rpetersky/gee_asset_manager/gee_asset_manager/batch_uploader.py", line 133, in __upload_to_gcs_and_start_ingestion_task
    nodata=nodata_value)
  File "/Users/rpetersky/gee_asset_manager/gee_asset_manager/batch_uploader.py", line 210, in __upload_file
    upload_url = __get_upload_url(session)
  File "/Users/rpetersky/gee_asset_manager/gee_asset_manager/batch_uploader.py", line 198, in __get_upload_url
    _ = session.get('https://ee-api.appspot.com/assets/upload/geturl?')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 597, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 113, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects)
TooManyRedirects: Exceeded 30 redirects.

As far as I know I am not doing anything different. I am working on a MacOS with Yosemite and I am using Python 2.7.

**Comment by tracek** [comment]
Interesting, I am not observing anything like that on my side. Can you check to what sites it is redirecting you?

**Comment by tracek** [comment]
Unless there are no further updates on this one, I will close it in 7 days.
