### ISSUE TITLE
Delete not finding the directory to remove

### ISSUE THREAD

**Issue by herrtunante** [tracek/gee_asset_manager#41]
The delete functionality does not seem to work (after having uploading too many collections i am testing to remove some of them) 

when I run the command (the collection has this name! ): 
_geebam delete users/openforisinitiative/ECMWF_evpt_final_

It returns this message :
```
2018-01-08 22:46:52,888 :: oauth2client.transport :: INFO :: Attempting refresh to obtain initial access_token
2018-01-08 22:46:52,888 :: oauth2client.client :: INFO :: Refreshing access_token
Traceback (most recent call last):
  File "C:\opt\apps\Python27\Scripts\geebam-script.py", line 11, in <module>
    load_entry_point('geebam', 'console_scripts', 'geebam')()
  File "c:\users\faoadmin\git\gee_asset_manager\geebam.py", line 118, in main
    args.func(args)
  File "c:\users\faoadmin\git\gee_asset_manager\geebam.py", line 45, in delete_collection_from_parser
    delete(args.id)
  File "c:\users\faoadmin\git\gee_asset_manager\gee_asset_manager\batch_remover.py", line 29, in delete
    all_assets_names = [e['id'] for e in ee.data.getList({'id': root})]
  File "c:\opt\apps\python27\lib\site-packages\ee\data.py", line 172, in getList
    return send_('/list', params)
  File "c:\opt\apps\python27\lib\site-packages\ee\data.py", line 728, in send_
  raise ee_exception.EEException(json_content['error']['message'])
ee.ee_exception.EEException: No such folder or collection: 'users/openforisinitiative'
```

**Comment by tracek** [comment]
Hi @herrtunante - Since it works on my end, I am going to need some help. Some questions first!

0. Make sure you're up-to-date with geebam and earthengine-api.

1. Are you sure your user is permitted to modify the resource, i.e. part of the openforisinitiative? The error you got is typical for cases when for some reason the user can't access the data.

2. If yes, then can you create in your own GEE space a collection and try to delete it? 

3. Can you try to delete a single asset from users/openforisinitiative/ECMWF_evpt_final with `earthengine asset rm` command?

**Comment by herrtunante** [comment]
Hi Lukas, thanks for the fast answer!

Indeed I did a _>git pull_ followed by a _>pip install geebam --upgrade_ and now it all works fine!

I thought I had just recently installed geebam but it might have been a few months ago!

Thanks again for creating and maintaining this very helpful tool!

**Comment by tracek** [comment]
Good to hear that @herrtunante ! I am pretty sure it's obvious, but just for completeness I'd add `pip install -U earthengine-api`. Also, it's worth noting that `earthengine` command line tool now supports recursive delete.

Thanks and keep up the great work with Open Foris!
