### ISSUE TITLE
ConnectionAbortedError: [WinError 10053]

### ISSUE THREAD

**Issue by jiachengzhao** [tracek/gee_asset_manager#57]
Hi,

I was trying to batch upload some tifs in a virtualenv on Windows 10 but encountered somes problems. When I typed in codes like` geebam upload -u <my user name> --source path_to_directory_with_tif  --dest users/my folder `, it firstly runs well and I could see some informations:

> 2019-11-07 22:36:22,413 :: root :: INFO :: Running the browser in normal mode
> 2019-11-07 22:36:51,335 :: root :: INFO :: Browser closed.
> 2019-11-07 22:36:54,883 :: root :: INFO :: New collection users/zhao/test created

but then an error thrrown:

> Traceback (most recent call last):
  File "C:\Users\zhao\miniconda3\envs\ee\Scripts\geebam-script.py", line 11, in <module>
    load_entry_point('geebam', 'console_scripts', 'geebam')()
  File "c:\users\zhao\gee_asset_manager\geebam.py", line 153, in main
    args.func(args)
  File "c:\users\zhao\gee_asset_manager\geebam.py", line 73, in upload_from_parser
    tolerate_assets_already_exist=args.tolerate_assets_already_exist)
  File "c:\users\zhao\gee_asset_manager\gee_asset_manager\batch_uploader.py", line 92, in upload
    tolerate_assets_already_exist)
  File "c:\users\zhao\gee_asset_manager\gee_asset_manager\batch_uploader.py", line 170, in __find_remaining_assets_for_upload
    remote_assets = __get_asset_names_from_collection(path_remote)
  File "c:\users\zhao\gee_asset_manager\gee_asset_manager\batch_uploader.py", line 325, in __get_asset_names_from_collection
    assets_list = ee.data.getList(params={'id': collection_path})
  File "c:\users\zhao\miniconda3\envs\ee\lib\site-packages\ee\deprecation.py", line 32, in Wrapper
    return func(*args, **kwargs)
  File "c:\users\zhao\miniconda3\envs\ee\lib\site-packages\ee\data.py", line 463, in getList
    return send_('/list', params)
  File "c:\users\zhao\miniconda3\envs\ee\lib\site-packages\ee\data.py", line 1753, in send_
    response, content = send_with_backoff()
  File "c:\users\zhao\miniconda3\envs\ee\lib\site-packages\ee\data.py", line 1744, in send_with_backoff
    url, method=opt_method, body=payload, headers=headers)
  File "c:\users\zhao\miniconda3\envs\ee\lib\site-packages\google_auth_httplib2.py", line 198, in request
    uri, method, body=body, headers=request_headers, **kwargs)
  File "c:\users\zhao\miniconda3\envs\ee\lib\site-packages\httplib2\__init__.py", line 1957, in request
    cachekey,
  File "c:\users\zhao\miniconda3\envs\ee\lib\site-packages\httplib2\__init__.py", line 1622, in _request
    conn, request_uri, method, body, headers
  File "c:\users\zhao\miniconda3\envs\ee\lib\site-packages\httplib2\__init__.py", line 1528, in _conn_request
    conn.connect()
  File "c:\users\zhao\miniconda3\envs\ee\lib\site-packages\httplib2\__init__.py", line 1376, in connect
    raise socket_err
  File "c:\users\zhao\miniconda3\envs\ee\lib\site-packages\httplib2\__init__.py", line 1311, in connect
    self.sock = self._context.wrap_socket(sock, server_hostname=self.host)
  File "c:\users\zhao\miniconda3\envs\ee\lib\ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "c:\users\zhao\miniconda3\envs\ee\lib\ssl.py", line 808, in __init__
    self.do_handshake()
  File "c:\users\zhao\miniconda3\envs\ee\lib\ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "c:\users\zhao\miniconda3\envs\ee\lib\ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
  ConnectionAbortedError: [WinError 10053] An established connection was aborted by the 
  software in your host machine

Does anyone have same issue?

Some informations of my virtualenv:
Package                  Version        Location
------------------------ -------------- -------------------------------
absl-py                  0.8.1
asn1crypto               0.22.0
astor                    0.8.0
atomicwrites             1.3.0
attrs                    19.3.0
beautifulsoup4           4.8.1
cachetools               3.1.1
certifi                  2019.9.11
cffi                     1.10.0
chardet                  3.0.4
chromedriver-binary      78.0.3904.70.0
colorama                 0.4.1
cryptography             1.8.1
earthengine-api          0.1.204
future                   0.16.0
gast                     0.2.2
geebam                   0.1.5          c:\users\zhao\gee_asset_manager
google-api-core          1.14.3
google-api-python-client 1.7.11
google-auth              1.7.0
google-auth-httplib2     0.0.3
google-auth-oauthlib     0.4.1
google-cloud-core        1.0.3
google-cloud-storage     1.20.0
google-pasta             0.1.8
google-resumable-media   0.4.1
googleapis-common-protos 1.6.0
grpcio                   1.25.0
h5py                     2.10.0
httplib2                 0.14.0
idna                     2.8
implicit                 0.4.0
importlib-metadata       0.23
Keras-Applications       1.0.8
Keras-Preprocessing      1.1.0
Markdown                 3.1.1
mkl-service              2.3.0
more-itertools           7.2.0
numpy                    1.17.3
oauth2client             4.1.3
oauthlib                 3.1.0
opt-einsum               3.1.0
packaging                16.8
pip                      19.3.1
pluggy                   0.13.0
protobuf                 3.10.0
py                       1.8.0
pyasn1                   0.4.7
pyasn1-modules           0.2.7
pycparser                2.18
pyOpenSSL                17.0.0
pyparsing                2.2.0
PySocks                  1.6.6
pytest                   5.2.2
pytz                     2017.2
requests                 2.22.0
requests-oauthlib        1.2.0
requests-toolbelt        0.9.1
retrying                 1.3.3
rsa                      4.0
scipy                    1.3.1
selenium                 3.141.0
setuptools               41.6.0
simplejson               3.11.1
six                      1.13.0
soupsieve                1.9.5
tensorboard              2.0.1
tensorflow               2.0.0
tensorflow-estimator     2.0.1
termcolor                1.1.0
tqdm                     4.36.1
uritemplate              3.0.0
urllib3                  1.25.6
wcwidth                  0.1.7
Werkzeug                 0.16.0
wheel                    0.33.6
win-inet-pton            1.0.1
wincertstore             0.2
wrapt                    1.11.2
zipp                     0.6.0

Many thanks for your help.

**Comment by jiachengzhao** [comment]
It worked once just when I disable the Windows Defender! but now it failed again...(with the Defender still closed)

**Comment by jiachengzhao** [comment]
Add python (C:\Users\zhao\miniconda3\envs\ee\python.exe, in my case) to the white lists of Windows Defender solved my problem.
