### ISSUE TITLE
ChromeDriver - any advice on how to debug?

### ISSUE THREAD

**Issue by DapperMapper14** [tracek/gee_asset_manager#60]
```
DevTools listening on ws://127.0.0.1:62883/devtools/browser/831ea98e-4d78-41f2-bf1f-11140f937c3e
Traceback (most recent call last):
  File "C:\Users\jonat\Anaconda3\envs\gee\Scripts\geebam-script.py", line 11, in <module>
    load_entry_point('geebam', 'console_scripts', 'geebam')()
  File "c:\users\jonat\gee_asset_manager\geebam.py", line 150, in main
    args.func(args)
  File "c:\users\jonat\gee_asset_manager\geebam.py", line 70, in upload_from_parser
    tolerate_assets_already_exist=args.tolerate_assets_already_exist)
  File "c:\users\jonat\gee_asset_manager\gee_asset_manager\batch_uploader.py", line 83, in upload
    headless=headless)
  File "c:\users\jonat\gee_asset_manager\gee_asset_manager\session.py", line 48, in get_google_session
    driver = webdriver.Chrome(options=options)
  File "C:\Users\jonat\Anaconda3\envs\gee\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "C:\Users\jonat\Anaconda3\envs\gee\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\jonat\Anaconda3\envs\gee\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\jonat\Anaconda3\envs\gee\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\jonat\Anaconda3\envs\gee\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 79
```

**Comment by DapperMapper14** [comment]
Downloaded geebam today but am running into the above error message after entering my password. Any advice on how to debug this?

**Comment by kkraoj** [comment]
Your chromedriver is incompatible with your current Chrome browser. 
Download the correct chromedriver (in your case version 79) from https://chromedriver.chromium.org/downloads and save the `chromedriver.exe` file to your
"chromedriver_binary" directory (that directory is usually found in "Lib/site_packages" in your python environment.
