### ISSUE TITLE
Error when uploading to an ImageCollection

### ISSUE THREAD

**Issue by herrtunante** [tracek/gee_asset_manager#61]
I am running the geebam upload command with this result:
It seems that it is making a request to an unexisting REST API?

2019-12-16 19:46:26,883 :: googleapiclient.discovery_cache :: WARNING :: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "c:\opt\python38\lib\site-packages\googleapiclient\discovery_cache\__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\opt\python38\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\opt\python38\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\opt\python38\lib\site-packages\googleapiclient\discovery_cache\__init__.py", line 41, in autodetect
    from . import file_cache
  File "c:\opt\python38\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 40, in <module>
    raise ImportError(
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
2019-12-16 19:46:26,885 :: googleapiclient.discovery :: INFO :: URL being requested: GET https://earthengine.googleapis.com/$discovery/rest?version=v1alpha&prettyPrint=false
2019-12-16 19:46:28,233 :: googleapiclient.discovery :: INFO :: URL being requested: GET https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/algorithms?prettyPrint=false&alt=json
2019-12-16 19:46:29,555 :: googleapiclient.discovery :: INFO :: URL being requested: GET https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/assets/users/openforisearthmap?prettyPrint=false&alt=json
Password:

DevTools listening on ws://127.0.0.1:56808/devtools/browser/cbefb4a4-35cd-4d70-9f1b-6b3b794a454e
2019-12-16 19:46:53,245 :: root :: INFO :: Running the browser in normal mode
2019-12-16 19:47:00,990 :: root :: INFO :: Browser closed.
2019-12-16 19:47:01,000 :: googleapiclient.discovery :: INFO :: URL being requested: GET https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/assets/users/openforisearthmap/biodiversity_vulnerability?prettyPrint=false&alt=json
2019-12-16 19:47:01,172 :: root :: WARNING :: Collection users/openforisearthmap/biodiversity_vulnerability already exists
2019-12-16 19:47:01,185 :: googleapiclient.discovery :: INFO :: URL being requested: GET https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/assets/users/openforisearthmap/biodiversity_vulnerability?prettyPrint=false&alt=json
2019-12-16 19:47:01,751 :: googleapiclient.discovery :: INFO :: URL being requested: GET https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/assets/users/openforisearthmap/biodiversity_vulnerability:listAssets?alt=json
2019-12-16 19:47:01,940 :: root :: INFO :: Processing image 1 out of 314: C:\opt\gee_asset_manager\vulnerability\001-ecoregion-vulnerability.tif
2019-12-16 19:47:05,796 :: googleapiclient.discovery :: INFO :: URL being requested: POST https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/image:import?alt=json
2019-12-16 19:47:10,174 :: googleapiclient.discovery :: INFO :: URL being requested: POST https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/image:import?alt=json
2019-12-16 19:47:14,363 :: googleapiclient.discovery :: INFO :: URL being requested: POST https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/image:import?alt=json
2019-12-16 19:47:14,524 :: root :: ERROR :: Upload of 001-ecoregion-vulnerability has failed.
Traceback (most recent call last):
  File "c:\opt\python38\lib\site-packages\ee\data.py", line 338, in _execute_cloud_call
    return call.execute(num_retries=num_retries)
  File "c:\opt\python38\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "c:\opt\python38\lib\site-packages\googleapiclient\http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/image:import?alt=json returned "Each MissingData must have at least one value.">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\opt\gee_asset_manager\gee_asset_manager\batch_uploader.py", line 126, in upload
    task_id = __start_ingestion_task(asset_request)
  File "c:\opt\python38\lib\site-packages\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "c:\opt\python38\lib\site-packages\retrying.py", line 212, in call
    raise attempt.get()
  File "c:\opt\python38\lib\site-packages\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "c:\opt\python38\lib\site-packages\six.py", line 696, in reraise
    raise value
  File "c:\opt\python38\lib\site-packages\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "c:\opt\gee_asset_manager\gee_asset_manager\batch_uploader.py", line 195, in __start_ingestion_task
    _ = ee.data.startIngestion(task_id, asset_request)
  File "c:\opt\python38\lib\site-packages\ee\data.py", line 1414, in startIngestion
    operation = _execute_cloud_call(
  File "c:\opt\python38\lib\site-packages\ee\data.py", line 340, in _execute_cloud_call
    raise _translate_cloud_exception(e)
ee.ee_exception.EEException: Each MissingData must have at least one value.
2

**Comment by jeantallen** [comment]
I got that error too - it went away when I started using the --nodata argument.
