### ISSUE TITLE
This browser or app may not be secure.

### ISSUE THREAD

**Issue by kkraoj** [tracek/gee_asset_manager#62]
Firstly, thank you for working on this project. 

I just installed geebam. And I have an issue connecting to my google account. 
When I do `geebam upload something` and enter the password, a chrome window opens, Selenium types the username and password, but after that, a page appears saying the following: 

"This browser or app may not be secure. [Learn more](https://support.google.com/accounts/answer/7675428?hl=en) 
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in."

Is there a work-around for this?

This seems to be an issue for several 3rd party apps and seems to be related to the new Oauth2 requirements from Google: https://support.google.com/accounts/thread/22873505?hl=en

Things I tried:
1.  Followed the suggestions actions in https://support.google.com/accounts/thread/22873505?hl=en- switched off 2 step authentication and gave access to "less secure" apps to my Google account by visiting: https://support.google.com/accounts/thread/22873505?hl=en
2. Downgraded Chrome and chromedriver to version 73 (release in approx Oct 2018 I think) to check if this is an issue with new chrome. Downgrading did not help. 

I will post the complete error message below. It contains many errors like google.appengine not found but all those are merely warning related to cache and can be ignored according to https://github.com/googleapis/google-api-python-client/issues/817 and https://github.com/googleapis/google-api-python-client/issues/427.

**Comment by kkraoj** [comment]
```
$ geebam upload -u kkrao.j@gmail.com --source D:/Krishna/projects/vwc_from_radar/data/map/dynamic_maps/lfmc --dest users/kkraoj/lfm-mapper/lfmc_col --nodata -9999
2020-03-22 11:07:18,680 :: googleapiclient.discovery_cache :: WARNING :: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "c:\users\kkrao\appdata\local\conda\conda\envs\py36\lib\site-packages\googleapiclient\discovery_cache\__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\kkrao\appdata\local\conda\conda\envs\py36\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\kkrao\appdata\local\conda\conda\envs\py36\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\kkrao\appdata\local\conda\conda\envs\py36\lib\site-packages\googleapiclient\discovery_cache\__init__.py", line 42, in autodetect
    from . import file_cache
  File "c:\users\kkrao\appdata\local\conda\conda\envs\py36\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 41, in <module>
    "file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth"
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
2020-03-22 11:07:18,696 :: googleapiclient.discovery :: INFO :: URL being requested: GET https://earthengine.googleapis.com/$discovery/rest?version=v1alpha&prettyPrint=false
2020-03-22 11:07:19,612 :: googleapiclient.discovery_cache :: WARNING :: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "c:\users\kkrao\appdata\local\conda\conda\envs\py36\lib\site-packages\googleapiclient\discovery_cache\__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\kkrao\appdata\local\conda\conda\envs\py36\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\kkrao\appdata\local\conda\conda\envs\py36\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\kkrao\appdata\local\conda\conda\envs\py36\lib\site-packages\googleapiclient\discovery_cache\__init__.py", line 42, in autodetect
    from . import file_cache
  File "c:\users\kkrao\appdata\local\conda\conda\envs\py36\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 41, in <module>
    "file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth"
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
2020-03-22 11:07:19,612 :: googleapiclient.discovery :: INFO :: URL being requested: GET https://earthengine.googleapis.com/$discovery/rest?version=v1alpha&prettyPrint=false
2020-03-22 11:07:20,221 :: googleapiclient.discovery :: INFO :: URL being requested: GET https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/algorithms?prettyPrint=false&alt=json
2020-03-22 11:07:21,065 :: googleapiclient.discovery :: INFO :: URL being requested: GET https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/assets/users/kkraoj/lfm-mapper?prettyPrint=false&alt=json
Password:
[10436:17012:0322/110724.688:ERROR:install_util.cc(589)] Unable to create registry key HKLM\SOFTWARE\Policies\Google\Chrome for reading result=2

DevTools listening on ws://127.0.0.1:59915/devtools/browser/01654dfd-41ec-4aa2-933c-23654564370d
2020-03-22 11:07:26,879 :: root :: INFO :: Running the browser in normal mode
2020-03-22 11:07:37,431 :: root :: INFO :: Browser closed.
Traceback (most recent call last):
  File "C:\Users\kkrao\AppData\Local\conda\conda\envs\py36\Scripts\geebam-script.py", line 11, in <module>
    load_entry_point('geebam', 'console_scripts', 'geebam')()
  File "d:\krishna\projects\gee_asset_manager\geebam.py", line 150, in main
    args.func(args)
  File "d:\krishna\projects\gee_asset_manager\geebam.py", line 70, in upload_from_parser
    tolerate_assets_already_exist=args.tolerate_assets_already_exist)
  File "d:\krishna\projects\gee_asset_manager\gee_asset_manager\batch_uploader.py", line 83, in upload
    headless=headless)
  File "d:\krishna\projects\gee_asset_manager\gee_asset_manager\session.py", line 70, in get_google_session
    password_el = driver.find_element_by_name("password")
  File "c:\users\kkrao\appdata\local\conda\conda\envs\py36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 496, in find_element_by_name
    return self.find_element(by=By.NAME, value=name)
  File "c:\users\kkrao\appdata\local\conda\conda\envs\py36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "c:\users\kkrao\appdata\local\conda\conda\envs\py36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "c:\users\kkrao\appdata\local\conda\conda\envs\py36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"name","selector":"password"}
  (Session info: chrome=67.0.3396.79)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.17763 x86_641
```

**Comment by CGaffey** [comment]
Have you been able to find a solution? I have the same problem.

**Comment by kkraoj** [comment]
I did not find a solution. The workaround is I started using [GeeUp](https://github.com/samapriya/geeup) which is very similar to geebam. GeeUp worked without any issues as it uses Mozilla Firefox rather than Chrome. It also has greater support as the developer behind it is actively improving it.
