### ISSUE TITLE
Upload of image has failed: invalid syntax

### ISSUE THREAD

**Issue by DKchenliyuan** [tracek/gee_asset_manager#70]
Hi,
I receive the following errors when uploading:

2023-02-26 17:27:50,005 :: root :: WARNING :: Collection users/chenliyuan/GRWL already exists
2023-02-26 17:27:52,905 :: root :: INFO :: Collection already exists. 2 assets left for upload to users/chenliyuan/GRWL.
2023-02-26 17:27:52,906 :: root :: INFO :: Processing image 1 out of 2: C:\test\SL58.tif
2023-02-26 17:28:02,376 :: root :: ERROR :: Upload of SL58 has failed.
Traceback (most recent call last):
  File "C:\Program Files\gee_asset_manager-master\gee_asset_manager\batch_uploader.py", line 120, in upload
    use_multipart=multipart_upload)
  File "C:\Anaconda\envs\gee\lib\site-packages\retrying-1.3.4-py3.7.egg\retrying.py", line 56, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "C:\Anaconda\envs\gee\lib\site-packages\retrying-1.3.4-py3.7.egg\retrying.py", line 257, in call
    return attempt.get(self._wrap_exception)
  File "C:\Anaconda\envs\gee\lib\site-packages\retrying-1.3.4-py3.7.egg\retrying.py", line 301, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "C:\Anaconda\envs\gee\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "C:\Anaconda\envs\gee\lib\site-packages\retrying-1.3.4-py3.7.egg\retrying.py", line 251, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "C:\Program Files\gee_asset_manager-master\gee_asset_manager\batch_uploader.py", line 240, in __upload_file_gee
    upload_url = __get_upload_url(session)
  File "C:\Program Files\gee_asset_manager-master\gee_asset_manager\batch_uploader.py", line 233, in __get_upload_url
    d = ast.literal_eval(r.text)
  File "C:\Anaconda\envs\gee\lib\ast.py", line 46, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "C:\Anaconda\envs\gee\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    <!doctype html><html class="hcfe" data-page-type="ANSWER" lang="en"><head><title>Clear cache &amp; cookies - Computer - Google Account Help</title><meta content="email=no" name="format-detection"><meta content="follow,index" name="robots"><meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"><meta content="When you use a browser, like Chrome, it saves some information from websites in its cache and cookies. Clearing them fixes certain problems, like loading or formatting issues on sites.&#10;In Chrome" name="description"><link href="https://support.google.com/accounts/answer/32050?hl=en&amp;co=GENIE.Platform%3DDesktop" rel="canonical"><meta content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=3,user-scalable=yes" name="viewport"><style>@font-face{font-family:'Roboto';font-style:normal;font-weight:400;src:url(https://fonts.gstatic.com/s/roboto/v18/KFOmCnqEu92Fr1Mu4mxP.ttf)format('truetype');}@font-face{font-family:'Roboto';font-style:normal;font-weight:500;src:url(https://fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmEU9fBBc9.ttf)format('truetype');}@font-face{font-family:'Roboto';font-style:normal;font-weight:700;src:url(https://fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmWUlfBBc9.ttf)format('truetype');}</style><style>@font-face{font-family:'Google Sans';font-style:normal;font-weight:400;src:url(https://fonts.gstatic.com/s/googlesans/v16/4UaGrENHsxJlGDuGo1OIlL3Owps.ttf)format('truetype');}@font-face{font-family:'Google Sans';font-style:normal;font-weight:500;src:url(https://fonts.gstatic.com/s/googlesans/v16/4UabrENHsxJlGDuGo1OIlLU94YtzCwM.ttf)format('truetype');}</style><link href="https://fonts.googleapis.com/css2?family=Google+Sans+Text:wght@400;500;700&amp;display=swap" as="style" id="gst" rel="preload" nonce="Nnr9RF8Gr2HhuobPwon0"><script nonce="Nnr9RF8Gr2HhuobPwon0">document.getElementById('gst').addEventListener('load',function(){this.rel="stylesheet";});</script> <script nonce="Nnr9RF8Gr2HhuobPwon0">
    ^
SyntaxError: invalid syntax

This question is very confusing to me, any ideas would be helpful, thank you！

**Comment by DKchenliyuan** [comment]
@tracek I would appreciate your reply
